/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rubber_duck/scene.gltf -o src/components/RubberDuck.jsx 
Author: Xabier Garcia (https://sketchfab.com/XabS11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoony-rubber-ducky-8a6e661916b74f9caa1c20dd6fdf77ad
Title: Cartoony Rubber Ducky
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.lambert2SG} rotation={[-Math.PI / 2, 0, 0]} scale={0.033} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
